### ISSUE TITLE
Bugs in sparse data with missing nominal values

### ISSUE THREAD

**Issue by RinyChau** [renatopp/liac-arff#52] opened 2017-03-30 03:48 UTC
![image](https://cloud.githubusercontent.com/assets/4788801/24486813/8823a4e6-153e-11e7-942e-cfb62272c685.png)

Due to the default value str(0), it may causes BadNominalValue() error when data contains some missing nominal values.

**Comment by kyao** [comment] 2018-02-21 02:29
Because of the this bug, liac-arff cannot decode many OpenML datasets, such as https://www.openml.org/d/35002

The default behavior of Weka is to fill in the missing nominal value with the first value in the nominal specification list

**Comment by mfeurer** [comment] 2018-02-21 07:48
Thank you a lot for pointing this out, but I would argue that this is not a bug in liac-arff, but in the [arff specification](http://weka.wikispaces.com/ARFF%20%28stable%20version%29). This behavior is not defined there, and I am very hesitant to add functionality here which is undocumented behavior of the WEKA arff reader. In fact, we deactivated the datasets in question on OpenML because they are not valid arff.

Also, this is a known bug in WEKA with a workaround on the WEKA side:
> Warning: There is a known problem saving SparseInstance objects from datasets that have string attributes. In Weka, string and nominal data values are stored as numbers; these numbers act as indexes into an array of possible attribute values (this is very efficient). However, the first string value is assigned index 0: this means that, internally, this value is stored as a 0. When a SparseInstance is written, string instances with internal value 0 are not output, so their string value is lost (and when the arff file is read again, the default value 0 is the index of a different string value, so the attribute value appears to change). To get around this problem, add a dummy string value at index 0 that is never used whenever you declare string attributes that are likely to be used in SparseInstance objects and saved as Sparse ARFF files.

**Comment by mitar** [comment] 2018-02-21 07:51
@mfeurer This still available dataset fails with this error: https://www.openml.org/d/35002

**Comment by mfeurer** [comment] 2018-02-21 07:53
I am aware of that; however, the dataset is flagged as 'in preparation' which basically means that it's not ready for production use. Someone needs to download all QSAR datasets, fix the bug in them, and re-upload them

**Comment by mfeurer** [comment] 2018-03-14 08:14
Closing this as it is an issue with OpenML and WEKA.

**Comment by mfeurer** [comment] 2018-03-14 08:40
Reopening as WEKA can actually read this file :(

**Comment by mfeurer** [comment] 2018-08-07 12:24
Solved by #76, thanks to @jnothman .

**Closed by mfeurer** 2018-08-07 12:24 UTC
Labels: WEKA-inconsistency
