### ISSUE TITLE
Bad @ATTRIBUTE type at line 993

### ISSUE THREAD

**Issue by AlexisHe** [renatopp/liac-arff#58] opened 2017-07-21 16:03 UTC
i used emobase.conf in openSMILE
line 993 is @attribute emotion unknown
how com is this bad @attribute type?
can anyone fix this?
thx in advance

**Comment by mfeurer** [comment] 2017-07-21 23:50
Is this a duplicate of #59?

**Comment by AlexisHe** [comment] 2017-07-22 00:17
no duplicate


On 07/22/2017 07:50，Matthias Feurer<notifications@github.com> wrote：

Is this a duplicate of#59?

**Comment by tats-u** [comment] 2018-02-19 07:06
I got similar errors when making this library load arff files generated by openSMILE, and I think attributes definitions of arff files like the following make trouble:

```
@attribute emotion 0,1,2,3
```

**Comment by mfeurer** [comment] 2018-02-19 13:26
@tats-u could you please provide a full file generated by openSMILE which triggers this behaviour?

**Comment by tats-u** [comment] 2018-02-19 14:33
Here you are: [sample_arff.arff.txt](https://github.com/renatopp/liac-arff/files/1737109/sample_arff.arff.txt)

This causes the following error when you try to load it by `arff.load`:

```
  File "/home/tatsu16/anaconda3/envs/residue/lib/python3.6/site-packages/arff.py", line 896, in load
    return_type=return_type)
  File "/home/tatsu16/anaconda3/envs/residue/lib/python3.6/site-packages/arff.py", line 743, in decode
    raise e
  File "/home/tatsu16/anaconda3/envs/residue/lib/python3.6/site-packages/arff.py", line 739, in decode
    matrix_type=return_type)
  File "/home/tatsu16/anaconda3/envs/residue/lib/python3.6/site-packages/arff.py", line 677, in _decode
    attr = self._decode_attribute(row)
  File "/home/tatsu16/anaconda3/envs/residue/lib/python3.6/site-packages/arff.py", line 621, in _decode_attribute
    raise BadAttributeType()
arff.BadAttributeType: Bad @ATTRIBUTE type, at line 1945.
```

**Comment by mfeurer** [comment] 2018-02-19 15:19
I just skimmed the [arff guide](http://weka.wikispaces.com/ARFF%20%28stable%20version%29) and cannot find a description of the attribute type in question. Should this be a nominal attribute with the values, `1`, `2`, `3` and `4`? If yes, the correct syntax would be `{1, 2, 3, 4}`.

**Comment by tats-u** [comment] 2018-02-20 11:14
I think so.  OpenSMILE violates the specification of the ARFF format.  Would you want me to open an issue at https://github.com/naxingyu/opensmile/issues?

**Comment by mfeurer** [comment] 2018-02-20 12:37
Yes, that would be great.

**Comment by tats-u** [comment] 2018-02-20 17:18
I will do later, though developers of it seem to show a lackadaisical attitude because all opened issues are left unsolved.

**Comment by mfeurer** [comment] 2018-03-14 08:15
Closing this as OpenSMILE does not produce valid arff. Please add the curly braces manually as a workaround.

**Closed by mfeurer** 2018-03-14 08:15 UTC
